<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-M7RBPII" failures="3" tests="4" name="Test1" time="32.752" errors="0" timestamp="2025-05-29T23:09:13 IST">
  <testcase classname="testScript.LoginTest" name="verifyUserLoginWithInvalidCredentials" time="3.382">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testScript.LoginTest.verifyUserLoginWithInvalidCredentials(LoginTest.java:58)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLoginWithInvalidCredentials -->
  <testcase classname="testScript.LoginTest" name="verifyUserLoginWithInvalidUsernameandValidPassword" time="0.139">
    <failure type="java.lang.IllegalStateException" message="Cannot get a NUMERIC value from a STRING cell">
      <![CDATA[java.lang.IllegalStateException: Cannot get a NUMERIC value from a STRING cell
at org.apache.poi.xssf.usermodel.XSSFCell.typeMismatch(XSSFCell.java:987)
at org.apache.poi.xssf.usermodel.XSSFCell.getNumericCellValue(XSSFCell.java:260)
at utitlities.ExcelUtility.getIntegerData(ExcelUtility.java:38)
at testScript.LoginTest.verifyUserLoginWithInvalidUsernameandValidPassword(LoginTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLoginWithInvalidUsernameandValidPassword -->
  <testcase classname="testScript.LoginTest" name="verifyUserLoginWithValidUsernameAndInvalidPassword" time="1.089">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testScript.LoginTest.verifyUserLoginWithValidUsernameAndInvalidPassword(LoginTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserLoginWithValidUsernameAndInvalidPassword -->
  <testcase classname="testScript.LoginTest" name="verifyuserloginwithvalidcredentials" time="2.046"/>
</testsuite> <!-- Test1 -->
